server:
  port: 8301

spring:
  application:
    name: service-vod

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 39.101.73.81:8848 # nacos注册中心服务器地址


  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_vod?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:com/ohj/glkt/vod/mapper/xml/*.xml

# cos配置
tencent:
  cos:
    file:
      region: ap-guangzhou
      secretid: AKIDDE3fDKH0UmqhIfKvJWdcYP3e5HF3ppfL
      secretkey: by9D3hJp6CHcjaMxNZsDQcgeVCh2A5yh
      bucketname: glkt-1304791648



